.gitignore
.mdformat.toml
Pipfile
Pipfile.lock
README.md
doc/README.md
doc/explanation.md
doc/howto.md
doc/tutorial.md
src/affiliation.py
src/app.py
src/app_test.py
src/static/simple.css
src/templates/base.html
src/templates/edit.html
src/templates/index.html
src/templates/login.html
src/templates/signup.html
tasks.py

Breakdown of changes by file:
.gitignore:
-Added DS.Store
affiliation.py
-Added if statement, if value is null to be an empty string/list. This is so that None/null does not appear in input tags.
-Changed expected return value in _row_to_affilitiation. Return value type discrepancy was causing errors with get_by_id method.
-Added get_by_id method to return all the information associated with a specific ID passed.
app.py
-Added edit route to redirect user to edit page to edit a specific affiliation ID.
simple.css
-Added formatting for columns, buttons, etc.
Created edit.html
-Contents of the edit page.
-Cancel Edit button takes user back to main page.
-Some fields are editable as inputs, dropdowns, or textareas depending of data type for readability for user.
index.html
-Reordered header …

feat: edit page initial functionality

---

src/affiliation.py
src/app.py
src/app_test.py
src/templates/base.html
src/templates/edit.html
src/templates/index.html

This PR introduced the submit functionality where the users input can change the values in the database.
affiliation.py
- based on conversation, change expected data type to be a string.
- add save to DB method.
app.py
- refactor previous edit method to work for GET methods.
- create edit_post method for POST methods to pass user input data into save method.
base.html
- add space for flash messages.
edit.html
- add if statements for default dropdown functionality.
- add name attribute to work with form functionality.
index.html
- remove unused scrollable class.
- reorder column layout.
- refactor edit path.

feat: edit submit to db functionality

---

src/main/urls.py

Remove "admin/" path and refactor so that base path ("") leads to the built in admin site. Related to [Issue 89](https://github.com/ClinGen/stanford-affils/issues/89). 
Close 89

feat: update urls.py

---

Pipfile
Pipfile.lock
src/main/settings.py

Description
- install Daphne and pin version
- add ASGI runserver compatibility
N/A
Checklist

feat: Add ASGI and Daphne

---

.env.template
.github/workflows/check.yml
.gitignore
Pipfile
Pipfile.lock
doc/tutorial.md
src/affiliations/admin.py
src/affiliations/tests.py
src/main/settings.py

Description
- Change python reference to 3.10 and dependencies.
- Change allowed hosts.
- Move secret key.
- Add dotenv and references to load env variables.
- Fix validation error scope and references bug.
- Updated tests to accurately test fixed validation errors.
N/A
Checklist
 [X] I have created the necessary [tests](https://github.com/ClinGen/stanford-affils/src/app_test.py) to show my …

feat: changes necessary for deployment and demo

---

.env.template
Pipfile
Pipfile.lock
doc/tutorial.md
src/main/settings.py

Description
- Followed the documentation for django-dbbackup [listed here](https://django-dbbackup.readthedocs.io/en/stable/installation.html) and Amazon S3 backend usage documentation [listed here](https://github.com/jazzband/django-dbbackup/blob/master/docs/storage.rst#amazon-s3).
- Update env.template with new expected environment variables.
- Update tutorial.md with how to run database backup.
Closes #153 
Checklist
 [X] I have run required [code checks](https://github.com/ClinGen/stanford-affils/pull/how-to.md#run-code-checks) …

feat: Add database backup

---

doc/adr/0002-summary-of-decisions-thus-far.md

Description
- Create summary of decisions made thus far in the project.
- Summary includes:
> - Using Django and Django Admin
> - Using PosegresSQL
> - Using Unfold Admin
> - Using Custom Javascript
> - Using ASGI and Daphne
N/A
Checklist …

feat: create summary of decisions ADR

---

.github/workflows/check.yml
Pipfile
Pipfile.lock
doc/tutorial.md
src/main/settings.py

Description
- Install boto3 and watchtower
- Add tutorial documentation on how to add log lines.
- Utilized/followed this [set up documentation](https://dev.to/jordanahaines/django-and-cloudwatch-logging-in-a-place-you-can-see-3bc7) and the [watchtower documentation](https://kislyuk.github.io/watchtower/)
Closes #92 
Checklist
 [X] I have created the …

feat: add cloudwatch logging

---

CONTRIBUTING.md
doc/how-to.md

Description
- Move Postgres set up docs to how-to.md file
Closes #119 
Checklist
Screenshots / Recordings
N/A

feat: move postgres docs to how-to.md file

---

src/main/settings.py

Description
- Add test subdomain names to allowed_hosts and CSRF_trusted_origins
- N/A
Checklist
Screenshots / …

feat: update settings.py with test subdomain

---

Pipfile

Description
- remove python-dotenv from dev-packages since it is already in packages section.
Closes #129 
Checklist
 [X] I have updated any necessary …

build: Update pipfile

---

CONTRIBUTING.md

Description
- add conventional commit documentation
Closes #167 
Checklist
Screenshots / Recordings
N/A

docs: Update CONTRIBUTING.md - Conventional Commits

---

CONTRIBUTING.md

Description
- Add squash and merge documentation.
Closes #170  
Checklist
Screenshots / Recordings
N/A

docs: Update CONTRIBUTING.md - Squash and Merge

---

doc/how-to.md

Description
- update how-to.md with Invoke documentation.
Closes https://github.com/ClinGen/stanford-affils/issues/172
Checklist
 [X ] I have reviewed the [how-to guide](https://github.com/ClinGen/stanford-affils/pull/how-to.md) and the [contributing file](https://github.com/ClinGen/stanford-affils/CONTRIBUTING.md).
 [X] I have run required [code checks](https://github.com/ClinGen/stanford-affils/pull/how-to.md#run-code-checks) and resolved any blockers.
 [X] I have created the necessary [tests](https://github.com/ClinGen/stanford-affils/src/app_test.py) to show my changes are effective and work as intended.
 [X] I have updated any necessary …

docs: update how-to.md - Invoke Docs

---

src/scripts/load.py

Description
- Add is_deleted variable and helper function to return boolean value
N/A
Checklist
Screenshots / …

feat: CSV migration script updates

---

.env.template
Pipfile
Pipfile.lock
src/affiliations/tests.py
src/affiliations/views.py
src/main/settings.py

Description
- Followed the documentation here: https://pypi.org/project/django-cors-headers/
- This update fixes the CORS related errors received when attempting to access the API from the GCI-VCI
N/A
Checklist
 [X] I have thoroughly …

feat: add django-cors-headers

---

doc/tutorial.md

Update Docs with api endpoint and URL info

docs: Update tutorial.md

---

.github/workflows/check.yml
Pipfile
Pipfile.lock
src/affiliations/admin.py
src/main/settings.py

Description
- Update settings.py and admin.py to handle export functionality
- Followed the installation guides for [django-import-export](https://django-import-export.readthedocs.io/en/latest/installation.html) and [unfold admin integration](https://unfoldadmin.com/docs/integrations/django-import-export/).
- Remove members column from export
- Include soft-deleted affiliations
Closes #223 
Checklist
 [X] I have run required [code checks](https://github.com/ClinGen/stanford-affils/pull/how-to.md#run-code-checks) and resolved any …

feat: Add CSV export functionality

---

src/affiliations/views.py

Description
- Add validation to not add duplicate approvers in response.
N/A
Checklist
Screenshots / Recordings …

fix: Approver duplicates in API response.

---

.gitignore
doc/tutorial.md
src/affiliations/models.py

For https://github.com/ClinGen/gci-vci-aws/issues/1730

Add CDWG type

---

doc/api_information.md
src/affiliations/serializers.py
src/affiliations/tests.py
src/affiliations/urls.py
src/affiliations/views.py

These are all of the same changes made in this[ PR request](https://github.com/ClinGen/stanford-affils/pull/295). I merged that PR into branch 'gs-post-request' and not on 'main'.
Description
Add update endpoint and view.
Refactor serializers.py update function.
Add and refactor tests.py
https://github.com/ClinGen/stanford-affils/pull/293
Checklist
 [X ] I have reviewed the [how-to guide](https://github.com/ClinGen/stanford-affils/pull/how-to.md) and the [contributing file](https://github.com/ClinGen/stanford-affils/CONTRIBUTING.md).
 [X] I have run required [code checks](https://github.com/ClinGen/stanford-affils/pull/how-to.md#run-code-checks) and resolved any blockers.
 [X] I have created the necessary …

feat: add update PATCH request endpoint

---

src/affiliations/admin.py
src/affiliations/serializers.py
src/affiliations/tests.py
src/affiliations/utils.py

Description
CDWG is an editable field and had validation to check against "type" while being created. This makes it so that it is also checked during updates.
- Break validate_and_set_expert_panel_id() into two functions in utils.py
- Refactor serializers.py and admin,py to validate cdwg against type on creation and update.
- Update tests
N/A
Checklist
 [X] I have created the …

fix: validate CDWG on update

---

doc/api_information.md
src/affiliations/tests.py
src/affiliations/urls.py
src/affiliations/views.py

One of the requests from Seth.

Add affiliation UUID route
